modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory
license="GNU GPL v3"
[[mods]] #mandatory
modId="mob_statues" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Mob Statues" #mandatory
authors="Cyborgmas" #optional
description='''
Adds mob statues.
'''
[[dependencies.mob_statues]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.mob_statues]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
